plugins {
	id 'java'
}

group = 'org.omnione.did'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21 
}

repositories {
	mavenCentral()
}

jar {
    archiveBaseName.set('did-core-sdk-server') 
    archiveVersion.set('2.0.0')
    archiveClassifier.set('') 
}

dependencies {
	implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
	implementation 'com.google.guava:guava:33.2.1-jre'
	implementation 'org.hibernate:hibernate-validator:7.0.0.Final'
	implementation 'com.google.code.gson:gson:2.8.9'
	implementation 'org.projectlombok:lombok:1.18.34'
	implementation 'org.omnione.did:did-crypto-sdk-server:2.0.0'
	implementation 'org.omnione.did:did-datamodel-sdk-server:2.0.0'
	
	annotationProcessor 'org.projectlombok:lombok:1.18.34'
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
