evm.network.url=https://stage-chainapi.omnione.net/?token=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJta2xlZUByYW9uY29ycC5jb20iLCJ0b2tlblR5cGUiOiJBUEkiLCJpYXQiOjE3NzM4OTYyMTksImV4cCI6MjYzNzgwOTgxOX0.QEVQvLXbY4pWd6dpq90ibPaXsARKxgefhDVyjMF1Y6Zi2bG1J-QOQwYp7B6fWKFt8brXSeTnEYO_HtalabSmrZz2w8wysebMpZ2D2JJ82oZcguuh2y7NUpyRsrOU63TqNumTKf34zGsZcc6JCrJiG17vWeik8nz2UEgJpeOdPpSRltdsjYBAwT075Gj79BlAlIhflJhI1N1c5FGEBktiYBZgL6qJDXqFpjt0yoOU9b78SiPHyKLLnrrP78k8jSybE0mOaBIxqd73cQ1ISDXns-wM9ApYJGHEOC7IxRNgnNMnRqSug6R37a4g4QzAUZsm4K5xYHFqbQxIbjjhvBWQZw
evm.chainId=201210
evm.gas.limit=10000000
evm.gas.price=0
evm.connection.timeout=10000
evm.contract.address=0xB6d8f7E21ee903262AA65aA535649171FCC744cF
evm.contract.privateKey=0x931de3deb12142f891431ee24e78dadf0229052ac0889a4cb3f7f9f94a16cc01