spring:
  profiles:
    active: dev, lss

wallet:
  file-path: /Users/yundabal/git/pqc/server-scripts/jars/Verifier/verifier-pqc.wallet
  password: omnioneopendid12!@
springdoc:
  server:
    url: http://10.48.17.123:6060

observer:
  url: http://127.0.0.1:18080
  service-name: did-verifier-server
