plugins {
	id 'java'
}

group = 'org.omnione.did'

java {
	sourceCompatibility = '21'
}

jar {
    archiveBaseName.set('pqc-did-crypto-sdk-server')
    archiveVersion.set('2.0.0')
    archiveClassifier.set('') 
}


repositories {
	mavenCentral()		
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.80' // forten - PQC ML-DSA-44 지원을 위해 1.78.1 → 1.80 업그레이드
}


